esphome:
  name: ${name}
  comment: EAN Reader
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True
  project:
    name: JayGray.EanReader
    version: "0.0.3"

external_components:
  - source: github://hlfcode/esphome/esphome@main
    components: [http_request]

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:
  level: ${log_level}
# Enable Home Assistant API

api:

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

http_request:

wifi:

improv_serial:

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
