esphome:
  on_boot:
    - priority: 600
      then:
        - switch.turn_on: switch_led_green

binary_sensor:
  - platform: gpio
    id: switch_read_state
    internal: true
    pin:
      number: GPIO18
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.turn_on: in_or_out
        - switch.template.publish:
            id: in_or_out
            state: ON
        - delay: 30s
        - switch.turn_off: in_or_out
        - switch.template.publish:
            id: in_or_out
            state: OFF

output:
  - platform: ledc
    pin: GPIO23
    id: rtttl_out

  - platform: ledc
    pin: GPIO25
    id: led_red
    inverted: true

  - platform: ledc
    pin: GPIO26
    id: led_green
    inverted: true

  - platform: ledc
    pin: GPIO27
    id: led_blue
    inverted: true

light:
  - platform: rgb
    id: indicator_light
    internal: true
    red: led_red
    green: led_green
    blue: led_blue

switch:
  - platform: template
    id: in_or_out
    name: In-/Outgoing
    turn_on_action:
      - switch.turn_on: switch_led_blue
    turn_off_action:
      - switch.turn_on: switch_led_green

  - platform: template
    id: switch_led_red
    internal: true
    turn_on_action:
      - light.turn_on:
          id: indicator_light
          brightness: 50%
          red: 100%
          green: 0
          blue: 0
          transition_length: 0ms
    turn_off_action:
      - light.turn_off:
          id: indicator_light
          transition_length: 0ms

  - platform: template
    id: switch_led_green
    internal: true
    turn_on_action:
      - light.turn_on:
          id: indicator_light
          brightness: 50%
          red: 0
          green: 100%
          blue: 0
          transition_length: 0ms
    turn_off_action:
      - light.turn_off:
          id: indicator_light
          transition_length: 0ms

  - platform: template
    id: switch_led_blue
    internal: true
    turn_on_action:
      - light.turn_on:
          id: indicator_light
          brightness: 50%
          red: 0
          green: 0
          blue: 100%
          transition_length: 0ms
    turn_off_action:
      - light.turn_off:
          id: indicator_light
          transition_length: 0ms

  - platform: template
    id: blink_led_green
    internal: true
    turn_on_action:
      - switch.turn_off: switch_led_green
      - switch.turn_off: switch_led_blue
      - delay: 500ms
      - switch.turn_on: switch_led_green
      - delay: 500ms
      - switch.turn_off: switch_led_green
      - delay: 500ms
      - switch.turn_on: switch_led_green
      - if:
          condition:
            - switch.is_on: in_or_out
          then:
            switch.turn_on: switch_led_blue
          else:
            switch.turn_on: switch_led_green

  - platform: template
    id: blink_led_red
    internal: true
    turn_on_action:
      - switch.turn_off: switch_led_green
      - switch.turn_off: switch_led_blue
      - delay: 500ms
      - switch.turn_on: switch_led_red
      - delay: 500ms
      - switch.turn_off: switch_led_red
      - delay: 500ms
      - switch.turn_on: switch_led_red
      - if:
          condition:
            - switch.is_on: in_or_out
          then:
            switch.turn_on: switch_led_blue
          else:
            switch.turn_on: switch_led_green

rtttl:
  output: rtttl_out
  on_finished_playback:
    - logger.log: "Song ended!"

