esphome:
  on_boot:
    priority: -100
    then:
      - button.press: get_gm60_firmware

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200
  debug:
    direction: BOTH
    dummy_receiver: true
    after:
      delimiter: "\r\n"
    sequence:
      - lambda: |-
          UARTDebug::log_string(direction, bytes);
          std::string str(bytes.begin(), bytes.end());

button:
  - platform: template
    id: get_gm60_firmware
    internal: True
    entity_category: config
    disabled_by_default: True
    on_press:
      then:
        - uart.write:
            id: uart_bus
            data: [0x7E, 0x00, 0x07, 0x01, 0x0000, 0x00FF, 0x00, 0xAB, 0xCD]
        - lambda: |-
          uint8_t response[20];
          if (id(uart_bus).read_array(response, 20)) {
            sprintf(response);
          }
